!!python/object:argparse.Namespace
activation: gelu
alpha: 5
attn: prob
batch_size: 32
c_out: 1
checkpoints: ./checkpoints/
cols: null
d_ff: 2048
d_layers: 1
d_model: 512
data: SRL_NEG_00_04
data_path: SRL_NEG_00_04.csv
dec_in: 1
des: test
detail_freq: d
devices: 0,1,2,3
distil: true
do_predict: false
dropout: 0.05
e_layers: 2
embed: timeF
enc_in: 1
factor: 5
features: S
freq: d
gpu: 0
inverse: false
itr: 1
label_len: 48
learning_rate: 0.0001
linex_weight: 0.001
loss: linex
lradj: type1
mix: true
model: informer
n_heads: 8
num_workers: 0
output_attention: false
padding: 0
patience: 3
pred_len: 3
root_path: ./data/processed/SRL/
s_layers:
- 3
- 2
- 1
seq_len: 96
target: capacity_price
timestamp: 05-05-2023_13-26-47
train_epochs: 1
use_amp: false
use_gpu: false
use_multi_gpu: false
